name: pet_charity
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2
  # 存储
  shared_preferences: ^2.0.18
  # 图片选择
  image_picker: ^0.8.7
  # url_launcher
  url_launcher: ^6.1.10
  #  go_router: ^6.0.10

  # 网络请求
  dio: ^5.0.3
  # svg图片
  flutter_svg: ^2.0.4
  # 图片
  cached_network_image: ^3.2.3
  # 自适应
  flutter_screenutil: ^5.7.0
  # 状态管理
  provider: ^6.0.5
  # toast
  bot_toast: ^4.0.3
  # 路由管理
  fluro: ^2.0.4
  # 下拉刷新
  easy_refresh: ^3.3.1
  # 裁剪
  image_cropper: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/public/
    - assets/main/
    - assets/home/
    - assets/question/
    - assets/personal/
    - assets/pet/
    - assets/donate/
    - assets/login/
    - assets/keyboard/
    - assets/search/
